# Generated by Django 3.0.3 on 2020-02-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avail_status',
            field=models.TextField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=20),
        ),
    ]
