# Generated by Django 3.0.3 on 2020-02-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('studentName', models.TextField(max_length=255)),
                ('phone_number', models.TextField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('schedule_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending')], max_length=9)),
            ],
        ),
    ]
