# Generated by Django 3.0.3 on 2020-02-18 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='stafalty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_scheduled', to=settings.AUTH_USER_MODEL),
        ),
    ]
